### ISSUE TITLE
Plugin installiert, bekomme aber timeout

### ISSUE THREAD

**Issue by Gregor-de** [bombadiltom/homebridge-rademacher-homepilot#123]
Hallo,
ich habe gerade das Plugin installiert. Homebridge läuft einem Pi4 mit Raspian. Passwort aus dem Homepilot2 habe ich erstmal entfernt. Den HP2 kann ich im Browser unter der IP-Adresse erreichen.
 Wenn ich Homebridge starte bekomme ich 3 analoge Fehlermeldungen mit einem timeout.

[17.3.2023, 14:20:52] [RademacherHomePilot] GET error for path http://192.168.0.13/v4/devices?devtype=Actuator: Error: timeout of 30000ms exceeded
    at createError (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/axios/lib/adapters/http.js:303:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  config: [Object],
  code: 'ECONNABORTED',
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
[17.3.2023, 14:20:52] [RademacherHomePilot] Request failed: Error: timeout of 30000ms exceeded
[17.3.2023, 14:20:52] [RademacherHomePilot] GET error for path http://192.168.0.13/v4/devices?devtype=Sensor: Error: timeout of 30000ms exceeded
    at createError (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/axios/lib/adapters/http.js:303:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  config: [Object],
  code: 'ECONNABORTED',
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
[17.3.2023, 14:20:52] [RademacherHomePilot] Request failed: Error: timeout of 30000ms exceeded
[17.3.2023, 14:20:52] [RademacherHomePilot] GET error for path http://192.168.0.13/v4/scenes: Error: timeout of 30000ms exceeded
    at createError (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/axios/lib/adapters/http.js:303:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/var/lib/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  config: [Object],
  code: 'ECONNABORTED',
  request: [Writable],
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
[17.3.2023, 14:20:52] [RademacherHomePilot] Request failed: Error: timeout of 30000ms exceeded

was könnte die Ursache sein?
Netzwerk kann es nicht sein, denn ich erreiche den HP2 ja von der gleichen Maschine.

Gruß
Gregor

**Comment by Gregor-de** [comment]
war doch mein Fehler :)
