### ISSUE TITLE
issue? - TypeError: Cannot read property 'url' of null

### ISSUE THREAD

**Issue by luissimoes** [bombadiltom/homebridge-rademacher-homepilot#20]
Hi
I was browsing the err file in /var/log (can't make my Homebridge start after Pi boot...) and found this entry
"
TypeError: Cannot read property 'url' of null
 at new RademacherHomePilot (/usr/lib/node_modules/homebridge-rademacher-homepilot/index.js:28:22)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
"

As I  don't really know what is going on in the code - I decided to ask here for a check...

many thanks!!!! (and equally many thanks for the excellent work!!!)
Luis

**Comment by luissimoes** [comment]
I've been looking at the system this time and seems... I was reading the err in var/log and not in journalctl logs... I think this was not correct.
Closing issue
