### ISSUE TITLE
Homebridge Crash durch Rauchmelder

### ISSUE THREAD

**Issue by canoben** [bombadiltom/homebridge-rademacher-homepilot#35]
Hallo, 

der Crash wird durch den Rauchalarmmelder veursacht, denn wenn ich ihn abmelde am Homepilot funktioniert Homebridge wieder:

`[11/5/2019, 7:13:03 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at new RademacherSmokeAlarmAccessory (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSmokeAlarmAccessory.js:17:20)
    at /homebridge/node_modules/homebridge-rademacher-homepilot/index.js:140:58
    at Array.forEach (<anonymous>)
    at handleSensors (/homebridge/node_modules/homebridge-rademacher-homepilot/index.js:128:33)
    at Request._callback (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at Request.self.callback (/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1083:12)
`

Der Crash trat erstmals mit der neuen Version 0.3.4 auf, da der Rauchmelder vorher zwar nicht in Homekit angezeigt wurde, aber auch keinen Crash produzierte.

**Comment by bombadiltom** [comment]
I added a battery service, please try "rm -f /etc/homebridge/accessories/cachedAccessories"

**Comment by canoben** [comment]
Don't I have to wait for a new version of the plugin first?

**Comment by bombadiltom** [comment]
No

Best mobile regards,

Tom Lorenz

**Comment by canoben** [comment]
Just out of curiosity: how is this possible? Is the docker image not completely self-contained, are there parts that are loaded dynamically from the net?

**Comment by bombadiltom** [comment]
The accessories are cached and if a new Service is implemented the cached version does not contain this and so the cache has to be cleared.
