### ISSUE TITLE
Abbruch beim Start der Homebridge

### ISSUE THREAD

**Issue by trichte** [bombadiltom/homebridge-rademacher-homepilot#39]
Hallo Tom,

wenn ich die Homebridge starte erhalte ich folgende Fehlermeldung aus dem Rademacher plugin.
Ich habe Version 4.0 installiert.

Kannst du hier helfen?

Danke
Thomas

Anbei die Logs, direkt vom Start:

[2020-1-4 18:57:42] Homebridge is running on port 51826.
[2020-1-4 18:57:42] [RademacherHomePilot] GET error for path http://192.168.2.119/v4/devices?devtype=Actuator: Error: conn         ect ECONNREFUSED 192.168.2.119:80
[2020-1-4 18:57:42] Error: Request failed: Error: connect ECONNREFUSED 192.168.2.119:80
    at handleActuators (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:42:29)
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSessi         on.js:115:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js         :881:8)
    at ClientRequest.emit (events.js:185:15)
    at Socket.socketErrorListener (_http_client.js:394:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[2020-1-4 18:57:42] [RademacherHomePilot] GET error for path http://192.168.2.119/v4/devices?devtype=Sensor: Error: connec         t ECONNREFUSED 192.168.2.119:80
[2020-1-4 18:57:42] Error: Request failed: Error: connect ECONNREFUSED 192.168.2.119:80
    at handleSensors (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:126:29)
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSessi         on.js:115:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js         :881:8)
    at ClientRequest.emit (events.js:185:15)
    at Socket.socketErrorListener (_http_client.js:394:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[2020-1-4 18:57:42] [RademacherHomePilot] GET error for path http://192.168.2.119/v4/scenes: Error: connect ECONNREFUSED 1         92.168.2.119:80
[2020-1-4 18:57:42] Error: Request failed: Error: connect ECONNREFUSED 192.168.2.119:80
    at handleScenes (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:185:29)
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSessi         on.js:115:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:180:13)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js         :881:8)
    at ClientRequest.emit (events.js:185:15)
    at Socket.socketErrorListener (_http_client.js:394:9)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[2020-1-4 18:57:42] Got SIGTERM, shutting down Homebridge...
[2020-1-4 18:57:47] [Config] Homebridge Config UI X v4.6.7 is listening on :: port 8080

**Comment by bombadiltom** [comment]
Ist die IP-Adresse denn korrekt?

**Comment by bombadiltom** [comment]
Geht http://192.168.2.119/v4/devices?devtype=Actuator im Browser?

**Comment by trichte** [comment]
Danke ... habs hinbekommen

habe erst die caches accessories gelöscht und dann den PI nochmal komplett neu gestartet.

**Comment by trichte** [comment]
Hallo Tom,

jetzt läuft bei mir das Plugin. Vielen Dank für die tolle Entwicklung.

Ich habe aber nochmal Fragen zur Funktionsweise:

1) Aus dem Homepilot wird das Feld Description in die Home App übertragen, nicht aber das Feld Name. Ist das so korrekt?

2) Wenn ich die Description im Homepilot ändere wird das nicht in der Home App aktualisiert. Ist das so korrekt?

3) Meine definierten Szenen werden als Schalter in der Home App dargestellt. Ich hätte das als Automation erwartet. Ist das so korrekt?

4) Kann das Plugin schon die Kameras untersützen? Die Geräte sind in der Home App nicht angekommen.

5) Die Sensoren vom Umweltsensor als auch von den Thermostaten werden nicht unter Sensor für eine Automation gelistet. Dort finde ich nur die Rauchmelder und die Fenstersensoren.

Besten Dank schon mal im Vorraus
Thomas

**Comment by bombadiltom** [comment]
1. wenn Description leer ist, wird der Name genommen, so kann man eigene Namen vergeben, falls gewünscht
2. sollte beim Neustart der Homebridge geschehen, ansonsten cachedAccessories löschen
3. ist so umgesetzt, mehr als auslösen kann man ja eh nicht machen
4. nein, habe keine zum Testen
5. nehme ich mal als eigenen Issue auf

**Comment by trichte** [comment]
Danke die Antworten haben mir geholfen.
Kann man Dir für die Kamera Daten senden?

**Comment by bombadiltom** [comment]
Ja, Bitcoins ;-)
