### ISSUE TITLE
Plugin lässt Server stoppen 

### ISSUE THREAD

**Issue by ScharV** [bombadiltom/homebridge-rademacher-homepilot#61]
Hey, ich versuche jemanden zu helfen, dessen Hoobs Server nicht mehr startet.
Laut Logs ist das Rademacher Plugin dafür verantwortlich und sorgt dafür, dass der Service stoppt. Das Plugin ist frisch auf den neuesten Stand geupdated worden nur kommen wir nicht weiter. 
Das ist die Ausgabe der Logs:
28.10.2020, 19:18:39 [RademacherHomePilot] Initializing RademacherHomePilot platform...
28.10.2020, 19:18:39 [RademacherHomePilot] Warning. No password has been configured. Consider protecting access to your HomePilot.
28.10.2020, 19:18:39 [RademacherHomePilot] GET error for path undefined/v4/devices?devtype=Actuator: Error: Invalid URI "undefined/v4/devices?devtype=Actuator"
    at Request.init (/home/hoobs/.hoobs/node_modules/request/request.js:273:31)
    at new Request (/home/hoobs/.hoobs/node_modules/request/request.js:127:8)
    at request (/home/hoobs/.hoobs/node_modules/request/index.js:53:10)
    at /home/hoobs/.hoobs/node_modules/request/index.js:61:12
    at Function.get (/home/hoobs/.hoobs/node_modules/request/index.js:100:12)
    at RademacherHomePilotSession.get (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:110:18)
    at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/index.js:223:30
    at RademacherHomePilotSession.login (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:40:9)
    at RademacherHomePilot.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/index.js:221:26)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
28.10.2020, 19:18:39 Error: Request failed: Error: Invalid URI "undefined/v4/devices?devtype=Actuator"
    at handleActuators (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/index.js:44:29)
    at Request._callback (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.init (/home/hoobs/.hoobs/node_modules/request/request.js:273:17)
    at new Request (/home/hoobs/.hoobs/node_modules/request/request.js:127:8)
    at request (/home/hoobs/.hoobs/node_modules/request/index.js:53:10)
    at /home/hoobs/.hoobs/node_modules/request/index.js:61:12
    at Function.get (/home/hoobs/.hoobs/node_modules/request/index.js:100:12)
    at RademacherHomePilotSession.get (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:110:18)
    at /home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/index.js:223:30
    at RademacherHomePilotSession.login (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:40:9)
    at RademacherHomePilot.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-rademacher-homepilot/index.js:221:26)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] server for interface BidCos-RF. is listening on port 9090.
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] server for interface VirtualDevices. is listening on port 9093.
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] server for interface BidCos-Wired. is listening on port 9091.
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] server for interface HmIP-RF. is listening on port 9092.
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] Creating Local HTTP Client for CCU RPC Events
28.10.2020, 19:18:39 Got SIGTERM, shutting down Bridge...
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] Removing Event Server for Interface BidCos-RF.
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] Removing Event Server for Interface BidCos-Wired.
28.10.2020, 19:18:39 [HomeMatic CCU] [RPC] Removing Event Server for Interface HmIP-RF.

Es wäre schön, wenn es ein Workaround hierfür gäbe.
Gruß
Marvin

**Comment by bombadiltom** [comment]
Error: Invalid URI "undefined/v4/devices?devtype=Actuator"

-> Konfigurationsfehler

**Comment by ScharV** [comment]
Ah okay, in Hoobs oder bei dem Rademacher?

**Comment by bombadiltom** [comment]
Hoobs kenne ich nicht, das Plugin muss konfiguriert werden, es fehlt die Url, siehe Doku
