### ISSUE TITLE
Homebridge is not running anymore after update of the plugin

### ISSUE THREAD

**Issue by bojomojo** [bombadiltom/homebridge-rademacher-homepilot#71]
I am getting those errors:

TypeError: Cannot read property 'includes' of undefined
    at did_filter (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:34:45)
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:95:49
    at Array.filter (<anonymous>)
    at handleActuators (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/index.js:95:34)
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:119:13)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by bojomojo** [comment]
had to add the attributes to the json for it to fetch them and work:

,
        "did_list_usage": "none",
        "did_list: []

**Comment by bombadiltom** [comment]
happens only if debug is true, will fix it
