### ISSUE TITLE
constant errors - ESOCKETTIMEDOUT and ETIMEDOUT

### ISSUE THREAD

**Issue by luissimoes** [bombadiltom/homebridge-rademacher-homepilot#73]
For some time now I have seen these kind of errors in the logs....

I restart homebridge... everything is good for a bit... then they show up again

The ETIMEDOUT show apparently for everydevice///
the ESOCKETTIMEDOUT shows for some

The consequence is that after sometime the devices are not reachable in Home APP and I have to restart Homebridge ...

Thanks for helping!!!

Luis

______
GET error for path http://xxx.xxx.xxx.xxx/v4/devices/1010011: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ETIMEDOUT',
  connect: true
}
____
GET error for path http://xxx.xxx.xxx.xxx/v4/devices/1010005: Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:421:28)
    at ClientRequest.emit (events.js:315:20)
    at Socket.emitRequestTimeout (_http_client.js:709:9)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:327:22)
    at Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ESOCKETTIMEDOUT',
  connect: false

**Comment by bombadiltom** [comment]
this is a network problem, not a problem of the plugin

**Comment by luissimoes** [comment]
> this is a network problem, not a problem of the plugin

Hi Tom,
thanks for answering so quick!
ok... but why do I have this only in the Rademacher?.... the home pilot is near other servers, no other plugin has messages and the access point is 2 meters away so the wifi very strong

is there any way I can understand what can cause this?

thanks!
