### ISSUE TITLE
Error: ETIMEDOUT 

### ISSUE THREAD

**Issue by monza258** [bombadiltom/homebridge-rademacher-homepilot#75]
Hi, ich habe des öfteren Fehler das dann die Instanz abstürzt und ich meine Rollläden nicht mehr ansteuern kann. 

```
Jan 29 09:13:37 raspberrypi4 homebridge[4173]: [29/01/2021, 09:13:37] [RademacherHomePilot] Wohnzimmer Fenster Mitte [8] - error getting position: Error: Request failed: Error: ETIMEDOUT
Jan 29 09:13:37 raspberrypi4 homebridge[4173]:     at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
Jan 29 09:13:37 raspberrypi4 homebridge[4173]:     at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
Jan 29 09:13:37 raspberrypi4 homebridge[4173]:     at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
Jan 29 09:13:37 raspberrypi4 homebridge[4173]:     at Request.emit (events.js:315:20)
Jan 29 09:13:37 raspberrypi4 homebridge[4173]:     at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
Jan 29 09:13:37 raspberrypi4 homebridge[4173]:     at listOnTimeout (internal/timers.js:554:17)
Jan 29 09:13:37 raspberrypi4 homebridge[4173]:     at processTimers (internal/timers.js:497:7)
```

**Comment by bombadiltom** [comment]
hmmm. der Logeintrag besagt eigentlich, dass der Fehler korrekt abgefangen wurde, was steht danach im Log?

**Comment by monza258** [comment]
Das zeiht sich so durch. Kann dann die Rollläden auch nicht ansteuern. 
Hier mal das ganze Log.

```
[29/01/2021, 09:13:17] [RademacherHomePilot] GET error for path http://192.168.0.100/v4/devices/3: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[29/01/2021, 09:13:17] [RademacherHomePilot] Wohnzimmer Rollo links [3] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[29/01/2021, 09:13:17] [RademacherHomePilot] GET error for path http://192.168.0.100/v4/devices/6: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[29/01/2021, 09:13:17] [RademacherHomePilot] Wohnzimmer Terrasse [6] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[29/01/2021, 09:13:17] [RademacherHomePilot] GET error for path http://192.168.0.100/v4/devices/8: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[29/01/2021, 09:13:17] [RademacherHomePilot] Wohnzimmer Fenster Mitte [8] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[29/01/2021, 09:13:37] [RademacherHomePilot] GET error for path http://192.168.0.100/v4/devices/3: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[29/01/2021, 09:13:37] [RademacherHomePilot] Wohnzimmer Rollo links [3] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[29/01/2021, 09:13:37] [RademacherHomePilot] GET error for path http://192.168.0.100/v4/devices/6: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[29/01/2021, 09:13:37] [RademacherHomePilot] Wohnzimmer Terrasse [6] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[29/01/2021, 09:13:37] [RademacherHomePilot] GET error for path http://192.168.0.100/v4/devices/8: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[29/01/2021, 09:13:37] [RademacherHomePilot] Wohnzimmer Fenster Mitte [8] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by bombadiltom** [comment]
das heißt aber, dass das Plugin normal weiter läuft, nur die Verbindung zum HomePilot ist kaputt, da kann ich nichts dran ändern, was sagt denn "netstat -a"? Sind da vielleicht zu viele Verbindungen zum HomePilot offen?

**Comment by monza258** [comment]
Puhh kenne diesen Befehl nicht mal. Ich habe nur eine Instanz die den Status anruft. Gibt eine Möglichkeit nach einer solchen Meldung das Plugin automatisch neu starten zu lassen oder das das Plugin alle 5 min zb den Status anruft und dann neu startet wenn die Bridge nicht antwortet?

**Comment by bombadiltom** [comment]
leider nein

**Comment by blssed** [comment]
Hey, bei mir besteht das gleiche Problem, sobald er einmal angefangen hat ETIMEDOUT errors zu werfen hört er nicht mehr auf und gibts irgendwann der Homebridge sogar ein sigint.
Passiert meistens nach 1-3 Tagen Laufzeit der Homebridge, manchmal auch nach wenigen Stunden.
Während diese errors fliegen ist aber eigentlich alles erreichbar, auch von der Homebridge kann ich auf den Homepilot zugreifen, also die Verbindung ist eigentlich nicht tot oder gestört.
