### ISSUE TITLE
Error cannot read state -> hab nur neugestartet

### ISSUE THREAD

**Issue by clipse2004** [bombadiltom/homebridge-rademacher-homepilot#80]
Hey, 
sehr komisch, ich habe einfach nur meinen Raspberry neugestartet und seitdem kommt ständig dieser Fehler. Der HomePilot ist im Netzwerk erreichbar und auf der Oberfläche sowie in der App steuerbar.  Selbst wenn über WLAN versuche eine Verbindung aufzubauen und eine neue IP zuweise, gleiches Problem.  
Ergänzung: gehe ich zurück auf die vorige Version 0.6.8 habe ich keinerlei Probleme mehr -> bis jetzt :)

[9.2.2021, 00:17:07] [RademacherHomePilot] GET error for path http://192.168.178.17/v4/devices/1: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[9.2.2021, 00:17:07] [RademacherHomePilot] Rollo Schlafzimmer [1] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[9.2.2021, 00:17:07] [RademacherHomePilot] GET error for path http://192.168.178.17/v4/devices/2: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[9.2.2021, 00:17:07] [RademacherHomePilot] Rollo Terrassentür [2] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[9.2.2021, 00:17:07] [RademacherHomePilot] GET error for path http://192.168.178.17/v4/devices/3: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[9.2.2021, 00:17:07] [RademacherHomePilot] Rollo Wohnzimmer [3] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[9.2.2021, 00:17:07] [RademacherHomePilot] GET error for path http://192.168.178.17/v4/devices/4: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[9.2.2021, 00:17:07] [RademacherHomePilot] Rollo Küche [4] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[9.2.2021, 00:17:07] [RademacherHomePilot] GET error for path http://192.168.178.17/v4/devices/7: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[9.2.2021, 00:17:07] [RademacherHomePilot] großer Rollo Esszimmer [7] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[9.2.2021, 00:17:07] [RademacherHomePilot] GET error for path http://192.168.178.17/v4/devices/9: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[9.2.2021, 00:17:07] [RademacherHomePilot] kleiner Rollo Esszimmer [9] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[9.2.2021, 00:17:07] [RademacherHomePilot] GET error for path http://192.168.178.17/v4/devices/25: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[9.2.2021, 00:17:07] [RademacherHomePilot] Aktor Markise [25] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[9.2.2021, 00:17:07] [RademacherHomePilot] GET error for path http://192.168.178.17/v4/devices/11: Error: ETIMEDOUT
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
[9.2.2021, 00:17:07] [RademacherHomePilot] Rollo Badezimmer [11] - error getting position: Error: Request failed: Error: ETIMEDOUT
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherAccessory.js:39:29
    at Request._callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:117:13)
    at self.callback (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Timeout.<anonymous> (/usr/lib/node_modules/homebridge-rademacher-homepilot/node_modules/request/request.js:851:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by clipse2004** [comment]
ok auch die vorherige Version bringt nach einer gewissen Zeit den selben Fehler

**Comment by bombadiltom** [comment]
das hat nichts mit dem Plugin zu tun, ist Power Saving für WLAN deaktiviert?

**Comment by clipse2004** [comment]
Power Saving? Meinst du im HomePilot? Ich hatte es ja bis Lan und WLAN probiert.
Allerdings habe ich aktuell keine Probleme mehr.
Sorry für meine Ausdrucksweise, aber Netzwerk ist eine Hure 😂.  Auf einmal kein Problem mehr, als hätte ich sich selbst geheilt.
Ich schließe den Fall später sollte es wirklich laufen. 
Mir ist allerdings immer noch schleiherhaft woher dieses Problem auf einmal kam.

**Comment by bombadiltom** [comment]
https://www.elektronik-kompendium.de/sites/raspberry-pi/1912231.htm

**Comment by clipse2004** [comment]
Ne meine raspberrys laufen über Lan. Der Fehler ist wieder aufgetreten.
Ich hab keine Ahnung mehr, wie schon gesagt der HomePilot ist im Netzwerk ansprechbar und steuerbar

**Comment by clipse2004** [comment]
Und wenn ich auf den angegebenen Link klicke 
http://192.168.178.47/v4/devices/2
dann zeigt der mir das Gerät dort an :/

**Comment by clipse2004** [comment]
Yup anscheinend hattest du recht, ich hab den Homepiloten mal umgestöpselt und auf einmal hats funktioniert. 
Sehr seltsam, ich hatte an der Konfig wirklich überhaupt nichts verändert.
