### ISSUE TITLE
Wettersensor macht Probleme

### ISSUE THREAD

**Issue by clipse2004** [bombadiltom/homebridge-rademacher-homepilot#85]
Hi,
Hab grad dein Update gezogen, scheint so als mache der Wettersensor aber allerdings Probleme.
Sobald ich diesen exclude, funktioniert wieder alles. Anbei der Log:
[RademacherHomePilot] Wettersensor [26] - getCurrentTemperature()
[23.2.2021, 13:18:05] [RademacherHomePilot] Wettersensor [26] - getCurrentAmbientLightLevel()
[23.2.2021, 13:18:05] [homebridge-rademacher-homepilot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.
[23.2.2021, 13:18:05] [RademacherHomePilot] GET error for path http://192.168.178.32/v4/devices?devtype=Sensor: ReferenceError: found is not defined
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherEnvironmentSensorAccessory.js:70:9
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:103:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[23.2.2021, 13:18:05] [RademacherHomePilot] Wettersensor [26] - getCurrentAmbientLightLevel(): error=ReferenceError: found is not defined
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherEnvironmentSensorAccessory.js:70:9
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:103:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[23.2.2021, 13:18:06] [Homebridge UI] Running Command: sudo -E -n npm install -g homebridge-rademacher-homepilot@latest
[23.2.2021, 13:18:15] [RademacherHomePilot] Wettersensor [26] - getCurrentTemperature()
[23.2.2021, 13:18:15] [RademacherHomePilot] Wettersensor [26] - getCurrentAmbientLightLevel()
[23.2.2021, 13:18:15] [RademacherHomePilot] GET error for path http://192.168.178.32/v4/devices?devtype=Sensor: ReferenceError: found is not defined
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherEnvironmentSensorAccessory.js:70:9
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:103:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[23.2.2021, 13:18:15] [RademacherHomePilot] Wettersensor [26] - getCurrentAmbientLightLevel(): error=ReferenceError: found is not defined
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherEnvironmentSensorAccessory.js:70:9
    at /usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherHomePilotSession.js:103:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[23.2.2021, 13:18:15] [homebridge-rademacher-homepilot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected float and received undefined. See https://git.io/JtMGR for more info.

**Comment by clipse2004** [comment]
Leider ist der Fehler bei mir aber damit nicht behoben :(

[23.2.2021, 15:39:17] [RademacherHomePilot] Wettersensor [26] - getCurrentAmbientLightLevel()

/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherEnvironmentSensorAccessory.js:55
    callback(null,self.currentAmbientLightLevel);
                       ^
TypeError: Cannot read property 'currentAmbientLightLevel' of undefined
    at RademacherEnvironmentSensorAccessory.getCurrentAmbientLightLevel (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherEnvironmentSensorAccessory.js:55:24)
    at RademacherEnvironmentSensorAccessory.update (/usr/lib/node_modules/homebridge-rademacher-homepilot/accessories/RademacherEnvironmentSensorAccessory.js:97:10)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by bombadiltom** [comment]
sorry, can't test it

**Comment by bombadiltom** [comment]
should be fixed in 0.7.2

**Comment by clipse2004** [comment]
yep its fixed :) big thx
