### ISSUE TITLE
Error v 0.7.4 

### ISSUE THREAD

**Issue by Charly-Man** [bombadiltom/homebridge-rademacher-homepilot#89]
[2/24/2021, 12:33:45 PM] ReferenceError: self is not defined
    at RademacherSunSensorAccessory.<anonymous> (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:66:13)
    at RademacherSunSensorAccessory.getCurrentSunState (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:30:5)
    at RademacherSunSensorAccessory.update (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:55:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2/24/2021, 12:33:45 PM] ReferenceError: self is not defined
    at RademacherSunSensorAccessory.<anonymous> (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:66:13)
    at RademacherSunSensorAccessory.getCurrentSunState (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:30:5)
    at RademacherSunSensorAccessory.update (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:55:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2/24/2021, 12:33:45 PM] ReferenceError: self is not defined
    at RademacherSunSensorAccessory.<anonymous> (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:66:13)
    at RademacherSunSensorAccessory.getCurrentSunState (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:30:5)
    at RademacherSunSensorAccessory.update (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:55:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2/24/2021, 12:33:45 PM] ReferenceError: self is not defined
    at RademacherSunSensorAccessory.<anonymous> (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:66:13)
    at RademacherSunSensorAccessory.getCurrentSunState (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:30:5)
    at RademacherSunSensorAccessory.update (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:55:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2/24/2021, 12:33:45 PM] ReferenceError: self is not defined
    at RademacherSunSensorAccessory.<anonymous> (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:66:13)
    at RademacherSunSensorAccessory.getCurrentSunState (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:30:5)
    at RademacherSunSensorAccessory.update (/homebridge/node_modules/homebridge-rademacher-homepilot/accessories/RademacherSunSensorAccessory.js:55:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

**Comment by Charly-Man** [comment]
Danke läuft wieder ;-)
